### ISSUE TITLE
[feature] cvar to disable chat

### ISSUE THREAD

**Issue by pektezol** [Blenderiste09/SourceAutoRecord#58]
This could be useful when rendering a demo and chat (whether binds which use say instead of sar_hud_text or coop messages) messing with it.

**Comment by BiSaXa** [comment]
#8e5e1b7e3859b535307c183dcf413b0d23da39dc

**Comment by BiSaXa** [comment]
8e5e1b7e3859b535307c183dcf413b0d23da39dc

**Comment by mlugg** [comment]
There already exists a fairly simple command in the base game that hides the chat; no need to reinvent the wheel here (`hud_saytext_time 0`)
