### ISSUE TITLE
Portal Reloaded: Crash on plugin_load sar

### ISSUE THREAD

**Issue by thekovic** [Blenderiste09/SourceAutoRecord#67]
Using the newest version, the game crashes without any error message

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
This happens for me for the base game as well... So I don't think its just for portal reloaded.

Btw, I also got a small update before trying to launch the game, so maybe this small update broke things? I have no idea...

**Comment by DipekTheRabbit** [comment]
I have the same problem but not on portal reloaded but everywhere

**Comment by mlugg** [comment]
This is an old SAR repo. Go to https://s.portal2.sr/sar for the newest release. If it still doesn't work, re-open the issue there.
