### ISSUE TITLE
Portal 2 crashes on startup

### ISSUE THREAD

**Issue by JulesOnDrugs** [Blenderiste09/SourceAutoRecord#68]
Portal 2 kept crashing on startup. It worked fine when sar.dll was removed from the files, but when reintroduced and loaded, it would instantly crash.

There is also no error message. I've attached one of the crash reports below.
[2021-05-25_16.47.32.txt](https://github.com/Blenderiste09/SourceAutoRecord/files/6541081/2021-05-25_16.47.32.txt)

Edit: I've tried removing autoexec.cfg and then loading it manually and it still crashes. I've also updated my drivers, but that didn't do it either.

**Comment by zysim** [comment]
I am also getting the same crash and error when trying to load the DLL, both through the autoexec and manually. I have gone through the Troubleshooting section on the Wiki as well and I can confirm I've got both the .NET framework runtime and the VC redist already installed, and at the latest version, at least according to Windows.

**Comment by RoyDubnium** [comment]
Same problem here.

**Comment by RoyDubnium** [comment]
I figured it out. the problem is with the latest update of portal 2. SAR will probably be fixed soon. In the meantime, just downgrade to the previous release in the "Betas"  @zysim @JulesOnDrugs @Blenderiste09
![Beta](https://user-images.githubusercontent.com/72664566/120070355-fd6c9d00-c081-11eb-867d-a5a751686bc5.PNG)

**Comment by JulesOnDrugs** [comment]
@O3nboi Thank you. Haven't looked at this thread in a while and just saw this.

**Comment by RoyDubnium** [comment]
It is fixed. This is the new SAR:
https://github.com/p2sr/SourceAutoRecord @JulesOnDrugs

**Comment by zysim** [comment]
Honestly I've forgotten about this thread myself lmao. Thanks! And thanks @mlugg for making the fix!

**Comment by mlugg** [comment]
Whoops, sorry, I somehow entirely missed this issue! Yeah, there was an update that broke SAR, and the repo linked above is SAR's new home - I should probably update the README on this repo to point over there

**Comment by zysim** [comment]
Ah, I see. I'll keep tabs on that repo then :+1:
